"""migration

Revision ID: 531b697dc667
Revises: 97bce3b4f74f
Create Date: 2021-10-20 17:44:10.902824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531b697dc667'
down_revision = '97bce3b4f74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
