"""migration

Revision ID: 97bce3b4f74f
Revises: 
Create Date: 2021-10-20 16:41:47.884586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bce3b4f74f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_Staff_staff_id'), 'Staff', ['staff_id'], unique=False)
    op.create_table('Customers',
    sa.Column('cus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['Staff.staff_id'], ),
    sa.PrimaryKeyConstraint('cus_id')
    )
    op.create_index(op.f('ix_Customers_cus_id'), 'Customers', ['cus_id'], unique=False)
    op.create_table('Shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('shift_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['Staff.staff_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Shifts_id'), 'Shifts', ['id'], unique=False)
    op.create_table('Orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_name', sa.String(length=255), nullable=False),
    sa.Column('order_description', sa.String(length=255), nullable=False),
    sa.Column('order_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('cus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cus_id'], ['Customers.cus_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['Staff.staff_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_Orders_order_id'), 'Orders', ['order_id'], unique=False)
    op.create_table('Payments',
    sa.Column('pay_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('cus_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cus_id'], ['Customers.cus_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.order_id'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    op.create_index(op.f('ix_Payments_pay_id'), 'Payments', ['pay_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Payments_pay_id'), table_name='Payments')
    op.drop_table('Payments')
    op.drop_index(op.f('ix_Orders_order_id'), table_name='Orders')
    op.drop_table('Orders')
    op.drop_index(op.f('ix_Shifts_id'), table_name='Shifts')
    op.drop_table('Shifts')
    op.drop_index(op.f('ix_Customers_cus_id'), table_name='Customers')
    op.drop_table('Customers')
    op.drop_index(op.f('ix_Staff_staff_id'), table_name='Staff')
    op.drop_table('Staff')
    # ### end Alembic commands ###
